name: iOS SDK Release

on:
  workflow_dispatch:
    inputs:
      VERSION:
        required: true

jobs:
  release:
    runs-on: macOS-latest
    env:
      VERSION: ${{ github.event.inputs.VERSION }}
      GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate environment and no-location patch
        run: |
              env | grep -q '^VERSION=' || (echo "Required environment variable VERSION is not set" && exit 1)
              env | grep -q '^GITHUB_ACCESS_TOKEN=' || (echo "Required environment variable GITHUB_ACCESS_TOKEN is not set" && exit 1)
              env | grep -q '^COCOAPODS_TRUNK_TOKEN=' || (echo "Required environment variable COCOAPODS_TRUNK_TOKEN is not set" && echo exit 1)
              git apply Scripts/0001-DISABLE-LOCATION.patch || (echo "Disable location patch could not be successfully applied" && exit 1)
              git checkout .

      - name: Setup git config
        run: |
              git config user.email "developers@mparticle.com"
              git config user.name "mParticle Automation"

      - name: Update version numbers
        run: |
              sed -i '' 's/NSString \*const kMParticleSDKVersion = @".*/NSString *const kMParticleSDKVersion = @"'"$VERSION"'";/' mParticle-Apple-SDK/MPIConstants.m
              /usr/libexec/PlistBuddy -c "Set CFBundleShortVersionString $VERSION" Framework/Info.plist
              jq --indent 3 '. += {'"\"$VERSION\""': "'"https://github.com/mParticle/mparticle-apple-sdk/releases/download/$VERSION/mParticle_Apple_SDK.framework.zip"'"}' mParticle_Apple_SDK.json
              sudo npm install -g podspec-bump
              podspec-bump -w -i $VERSION
              git add mParticle-Apple-SDK/MPIConstants.m Framework/Info.plist; git add mParticle-Apple-SDK.podspec; git add mParticle_Apple_SDK.json; git commit -m "Update version to $VERSION"

      - name: Build repo artifacts
        run: |
              ./Scripts/make_artifacts.sh
              ls mParticle_Apple_SDK.framework.zip mParticle_Apple_SDK.framework.nolocation.zip mParticle_Apple_SDK.xcframework.zip mParticle_Apple_SDK.xcframework.nolocation.zip generated-docs.zip || exit 1


      - name: Push publicly to Github
        run: |
              git tag $VERSION
              git push origin HEAD:development
              git push origin HEAD:master
              git push origin $VERSION

      - name: Create GitHub release and upload repo artifacts
        run: |
              curl -v --data '{"tag_name": "'"$VERSION"'","target_commitish": "master","name": "Version '"$VERSION"'","body": "'"$RELEASE_BODY"'","draft": false,"prerelease": false}' https://api.github.com/repos/mac-ci-png/mparticle-apple-sdk/releases?access_token=$GITHUB_ACCESS_TOKEN | grep '^  "id": ' | sed 's/"id":[ ]*\([^,]*\),/\1/' > /tmp/release-id
              export RELEASE_ID="$(cat /tmp/release-id | sed 's/[ ]*//g')"
              curl -v "https://uploads.github.com/repos/mac-ci-png/mparticle-apple-sdk/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=mParticle_Apple_SDK.framework.zip" --header 'Content-Type: application/zip' --upload-file mParticle_Apple_SDK.framework.zip -X POST || true
              curl -v "https://uploads.github.com/repos/mac-ci-png/mparticle-apple-sdk/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=mParticle_Apple_SDK.framework.nolocation.zip" --header 'Content-Type: application/zip' --upload-file mParticle_Apple_SDK.framework.nolocation.zip -X POST || true
              curl -v "https://uploads.github.com/repos/mac-ci-png/mparticle-apple-sdk/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=mParticle_Apple_SDK.xcframework.zip" --header 'Content-Type: application/zip' --upload-file mParticle_Apple_SDK.xcframework.zip -X POST || true
              curl -v "https://uploads.github.com/repos/mac-ci-png/mparticle-apple-sdk/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=mParticle_Apple_SDK.xcframework.nolocation.zip" --header 'Content-Type: application/zip' --upload-file mParticle_Apple_SDK.xcframework.nolocation.zip -X POST || true
              curl -v "https://uploads.github.com/repos/mac-ci-png/mparticle-apple-sdk/releases/$RELEASE_ID/assets?access_token=$GITHUB_ACCESS_TOKEN&name=generated-docs.zip" --header 'Content-Type: application/zip' --upload-file generated-docs.zip -X POST || true

      - name: Release to CocoaPods
        run: |
              echo pod trunk push --allow-warnings
